export const formFields = {
    FIRST_NAME: 'first_name',
    LAST_NAME: 'last_name',
    EMAIL: 'email',
    PHONE: 'phone',
    SELECTED_SKILL: 'selected_skill',
    EXPERIENCE: 'experience',
    WORK_PREFERENCE: 'work_preference',
    HAD_COVID: 'had_covid',
    VACCINATED: 'vaccinated',
    COVID_DATE: 'covid_date',
    VACCINE_DATE: 'vaccine_date',
    ATTEND_DEV_TALKS: 'attend_dev_talks',
    DEV_TALK_TOPIC: 'dev_talk_topic',
    SOMETHING_SPECIAL: 'something_special',
}